In [1]:
import pandas as pd

In [ ]:
#TASK 1: Read the CSV file into a DataFrame
csv=pd.read_csv('./population.csv')

In [4]:
#display the first 5 rows of the dataset
csv.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [5]:
#shape of data
print("Shape of the dataset:", csv.shape)

Shape of the dataset: (25, 2)

In [9]:
#datatype
print("Data Type:\n", csv.dtypes)

Data Type:
 country         str
population    int64
dtype: object

In [11]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#TASK 2 Read the Population dataset from the CSV file. 
excel_data=pd.read_excel("./gdp.xlsx")
#display column names
print("Column Names:\n", excel_data.columns.tolist)

Column Names:
 <bound method IndexOpsMixin.tolist of Index(['Country', 'GDP'], dtype='str')>

In [15]:
#TASK 3
#read JSON file and convert it to a DataFrame
json_data=pd.read_json("./internet_users.json")
print(json_data)

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [17]:
#TASK 4
%pip install lxml
xml_file = pd.read_xml("./literacy_rate.xml")
#extract all required field into a DataFrame
df_xml = pd.DataFrame(xml_file)
print(df_xml)

Requirement already satisfied: lxml in c:\Users\avani\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.1.1)
Note: you may need to restart the kernel to use updated packages.
              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
#TASK-5
literacy_df = xml_file
population_df = csv
#Number of Rows
print("Number of Rows of gdp:", len(excel_data))
print("Number of rows of internet users:", len(json_data))
print("Number of rows of literacy rate:", len(literacy_df))
print("Number of rows of population:", len(population_df))


#Number of Columns
print("\nNumber of Columns of GDP:", len(excel_data.columns))
print("Number of Columns of Internet Users:", len(json_data.columns))
print("Number of Columns of Literacy Rate:", len(literacy_df.columns))
print("Number of Columns of Population:", len(population_df.columns))

#Column Names
print("\nGDP Column Names:", excel_data.columns.tolist())
print("Literacy Rate Column Names:", literacy_df.columns.tolist())
print("Population Column Names:", population_df.columns.tolist())


#Data Types
print(excel_data.dtypes)
print(json_data.dtypes)
print(literacy_df.dtypes)
print(population_df.dtypes)


#Missing Values
print(excel_data.isnull().sum())
print(json_data.isnull().sum())
print(literacy_df.isnull().sum())
print(population_df.isnull().sum())


#Duplicate Records
print(excel_data.duplicated().sum())
print(json_data.duplicated().sum())
print(literacy_df.duplicated().sum())
print(population_df.duplicated().sum())

Number of Rows of gdp: 25
Number of rows of internet users: 25
Number of rows of literacy rate: 25
Number of rows of population: 25

Number of Columns of GDP: 2
Number of Columns of Internet Users: 2
Number of Columns of Literacy Rate: 2
Number of Columns of Population: 2

GDP Column Names: ['Country', 'GDP']
Literacy Rate Column Names: ['name', 'literacy_rate']
Population Column Names: ['country', 'population']
Country      str
GDP        int64
dtype: object
country             str
internet_users    int64
dtype: object
name                 str
literacy_rate    float64
dtype: object
country         str
population    int64
dtype: object
Country    0
GDP        0
dtype: int64
country           0
internet_users    0
dtype: int64
name             0
literacy_rate    0
dtype: int64
country       0
population    0
dtype: int64
0
0
0
0

In [ ]:
#TASK 6

# Excel file
excel_data = pd.read_excel('gdp.xlsx')

# JSON file
json_data = pd.read_json('internet_users.json')

# XML file
literacy_df = pd.read_xml('literacy_rate.xml')

# CSV file
population_df = pd.read_csv('population.csv')
# Function to clean column names
def clean_columns(df):
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
    return df

# Apply cleaning
excel_data = clean_columns(excel_data)
json_data = clean_columns(json_data)
literacy_df = clean_columns(literacy_df)
population_df = clean_columns(population_df)

# Rename to common key column
literacy_df.rename(columns={'name': 'country'}, inplace=True)

# Display column names
print(excel_data.columns)
print(json_data.columns)
print(literacy_df.columns)
print(population_df.columns)

Index(['country', 'gdp'], dtype='str')
Index(['country', 'internet_users'], dtype='str')
Index(['country', 'literacy_rate'], dtype='str')
Index(['country', 'population'], dtype='str')

In [8]:
#TASK -7
excel_data['gdp'] = pd.to_numeric(excel_data['gdp'])
json_data['internet_users'] = pd.to_numeric(json_data['internet_users'])
literacy_df['literacy_rate'] = pd.to_numeric(literacy_df['literacy_rate'])
population_df['population'] = pd.to_numeric(population_df['population'])

print("Excel Data:\n", excel_data.dtypes)
print("JSON Data:\n", json_data.dtypes)
print("Literacy Data:\n", literacy_df.dtypes)
print("Population Data:\n", population_df.dtypes)

Excel Data:
 country      str
gdp        int64
dtype: object
JSON Data:
 country             str
internet_users    int64
dtype: object
Literacy Data:
 country              str
literacy_rate    float64
dtype: object
Population Data:
 country         str
population    int64
dtype: object

In [ ]:
#TASK 8
merged_df = pd.merge(excel_data, json_data)
merged_df = pd.merge(merged_df, literacy_df)
merged_df = pd.merge(merged_df, population_df)

print(merged_df.head())

         country       gdp  internet_users  literacy_rate  population
0  United States  30500000       312000000           99.0   331002651
1          China  19230000      1080000000           97.2  1411778724
2          India   4187000       850000000           77.7  1380004385
3          Japan   4180000       118000000           99.0   125836021
4        Germany   4744000        79000000           99.0    83240525

In [ ]:
#TASK 9
# Internet Penetration (%)
merged_df['internet_penetration'] = (merged_df['internet_users'] / merged_df['population']) * 100
merged_df['internet_penetration'] = merged_df['internet_penetration'].round(2)

# GDP Per Capita
merged_df['gdp_per_capita'] = merged_df['gdp'] / merged_df['population']
merged_df['gdp_per_capita'] = merged_df['gdp_per_capita'].round(2)

# Show output
print(merged_df.head())

         country       gdp  internet_users  literacy_rate  population  \
0  United States  30500000       312000000           99.0   331002651
1          China  19230000      1080000000           97.2  1411778724
2          India   4187000       850000000           77.7  1380004385
3          Japan   4180000       118000000           99.0   125836021
4        Germany   4744000        79000000           99.0    83240525

   internet_penetration  gdp_per_capita
0                 94.26            0.09
1                 76.50            0.01
2                 61.59            0.00
3                 93.77            0.03
4                 94.91            0.06

In [11]:
#TASK 10
import sqlite3

# Create database (or connect if already exists)
conn = sqlite3.connect('country_data.db')

# Store DataFrame into table
merged_df.to_sql('country_statistics', conn, if_exists='replace', index=False)

# Close connection
conn.close()

print("Data stored successfully!")

Data stored successfully!

In [12]:
#TASK 11
import sqlite3


# Connect to database
conn = sqlite3.connect('country_data.db')

# Get first 5 rows
df = pd.read_sql("SELECT * FROM country_statistics LIMIT 5", conn)

# Show output
print(df)

# Close connection
conn.close()

         country       gdp  internet_users  literacy_rate  population  \
0  United States  30500000       312000000           99.0   331002651
1          China  19230000      1080000000           97.2  1411778724
2          India   4187000       850000000           77.7  1380004385
3          Japan   4180000       118000000           99.0   125836021
4        Germany   4744000        79000000           99.0    83240525

   internet_penetration  gdp_per_capita
0                 94.26            0.09
1                 76.50            0.01
2                 61.59            0.00
3                 93.77            0.03
4                 94.91            0.06

In [13]:
#PART E
#1 Sort data by GDP in descending order and get top 5
merged_df.sort_values(by='gdp', ascending=False).head(5)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,United States,30500000,312000000,99.0,331002651,94.26,0.09
1,China,19230000,1080000000,97.2,1411778724,76.50,0.01
4,Germany,4744000,79000000,99.0,83240525,94.91,0.06
2,India,4187000,850000000,77.7,1380004385,61.59,0.00
3,Japan,4180000,118000000,99.0,125836021,93.77,0.03

In [14]:
#2. Sort data by population in descending order and get top 5
merged_df.sort_values(by='population', ascending=False).head(5)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
1,China,19230000,1080000000,97.2,1411778724,76.50,0.01
2,India,4187000,850000000,77.7,1380004385,61.59,0.00
0,United States,30500000,312000000,99.0,331002651,94.26,0.09
15,Indonesia,1500000,212000000,96.0,273523615,77.51,0.01
10,Brazil,2330000,181000000,93.2,212559417,85.15,0.01

In [15]:
#3. Calculate mean (average) of literacy rate
merged_df['literacy_rate'].mean()

np.float64(97.248)

In [16]:
#4.Filter countries where literacy rate is greater than 90%
merged_df[merged_df['literacy_rate'] > 90]

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,United States,30500000,312000000,99.0,331002651,94.26,0.09
1,China,19230000,1080000000,97.2,1411778724,76.50,0.01
3,Japan,4180000,118000000,99.0,125836021,93.77,0.03
4,Germany,4744000,79000000,99.0,83240525,94.91,0.06
5,United Kingdom,3839000,66000000,99.0,67886011,97.22,0.06
6,France,3211000,62000000,99.0,65273511,94.98,0.05
7,Italy,2420000,56000000,99.0,60461826,92.62,0.04
8,Canada,2250000,36000000,99.0,38005238,94.72,0.06
9,Australia,1880000,24000000,99.0,25687041,93.43,0.07
10,Brazil,2330000,181000000,93.2,212559417,85.15,0.01
11,Russia,2200000,125000000,99.7,145934462,85.65,0.02
12,South Korea,1800000,50000000,98.8,51780579,96.56,0.03
13,Spain,1710000,44000000,98.6,46754778,94.11,0.04
14,Mexico,1810000,102000000,95.4,128932753,79.11,0.01
15,Indonesia,1500000,212000000,96.0,273523615,77.51,0.01
16,Saudi Arabia,1100000,34000000,97.3,34813871,97.66,0.03
17,Turkey,1350000,69000000,96.7,84339067,81.81,0.02
18,South Africa,410000,43000000,95.0,59308690,72.50,0.01
19,Argentina,640000,41000000,99.1,45195774,90.72,0.01
20,Netherlands,1150000,17000000,99.0,17441139,97.47,0.07
21,Switzerland,940000,8500000,99.0,8654622,98.21,0.11
22,Sweden,650000,10100000,99.0,10353442,97.55,0.06
23,Norway,580000,5300000,100.0,5421241,97.76,0.11
24,Singapore,530000,5600000,97.5,5850342,95.72,0.09

In [ ]:
#5.Filter countries where internet penetration is greater than 70%
merged_df[merged_df['internet_penetration'] > 70]

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,United States,30500000,312000000,99.0,331002651,94.26,0.09
1,China,19230000,1080000000,97.2,1411778724,76.50,0.01
3,Japan,4180000,118000000,99.0,125836021,93.77,0.03
4,Germany,4744000,79000000,99.0,83240525,94.91,0.06
5,United Kingdom,3839000,66000000,99.0,67886011,97.22,0.06
6,France,3211000,62000000,99.0,65273511,94.98,0.05
7,Italy,2420000,56000000,99.0,60461826,92.62,0.04
8,Canada,2250000,36000000,99.0,38005238,94.72,0.06
9,Australia,1880000,24000000,99.0,25687041,93.43,0.07
10,Brazil,2330000,181000000,93.2,212559417,85.15,0.01
11,Russia,2200000,125000000,99.7,145934462,85.65,0.02
12,South Korea,1800000,50000000,98.8,51780579,96.56,0.03
13,Spain,1710000,44000000,98.6,46754778,94.11,0.04
14,Mexico,1810000,102000000,95.4,128932753,79.11,0.01
15,Indonesia,1500000,212000000,96.0,273523615,77.51,0.01
16,Saudi Arabia,1100000,34000000,97.3,34813871,97.66,0.03
17,Turkey,1350000,69000000,96.7,84339067,81.81,0.02
18,South Africa,410000,43000000,95.0,59308690,72.50,0.01
19,Argentina,640000,41000000,99.1,45195774,90.72,0.01
20,Netherlands,1150000,17000000,99.0,17441139,97.47,0.07
21,Switzerland,940000,8500000,99.0,8654622,98.21,0.11
22,Sweden,650000,10100000,99.0,10353442,97.55,0.06
23,Norway,580000,5300000,100.0,5421241,97.76,0.11
24,Singapore,530000,5600000,97.5,5850342,95.72,0.09

In [ ]:
#6. Sort by GDP per capita and get top 5
merged_df.sort_values(by='gdp_per_capita', ascending=False).head(5)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
21,Switzerland,940000,8500000,99.0,8654622,98.21,0.11
23,Norway,580000,5300000,100.0,5421241,97.76,0.11
24,Singapore,530000,5600000,97.5,5850342,95.72,0.09
0,United States,30500000,312000000,99.0,331002651,94.26,0.09
9,Australia,1880000,24000000,99.0,25687041,93.43,0.07

In [ ]:
#7. Calculate total population using sum
merged_df['population'].sum()

np.int64(4720039725)

In [ ]:
#8. Calculate average internet penetration
merged_df['internet_penetration'].mean()

np.float64(89.6596)

In [ ]:
#9. Find the row where internet users is maximum
merged_df.loc[merged_df['internet_users'].idxmax()]

country                      China
gdp                       19230000
internet_users          1080000000
literacy_rate                 97.2
population              1411778724
internet_penetration          76.5
gdp_per_capita                0.01
Name: 1, dtype: object

In [ ]:
# 10.Find correlation between literacy rate and internet penetration
merged_df['literacy_rate'].corr(merged_df['internet_penetration'])

In [ ]:
# PART F
# Connect to SQLite database
conn = sqlite3.connect('country_data.db')

In [ ]:
#11. Select all columns, sort by GDP (highest first), show top 5
pd.read_sql("""
SELECT * FROM country_statistics
ORDER BY gdp DESC
LIMIT 5
""", conn)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,United States,30500000,312000000,99.0,331002651,94.26,0.09
1,China,19230000,1080000000,97.2,1411778724,76.50,0.01
2,Germany,4744000,79000000,99.0,83240525,94.91,0.06
3,India,4187000,850000000,77.7,1380004385,61.59,0.00
4,Japan,4180000,118000000,99.0,125836021,93.77,0.03

In [25]:
# 12.Calculate average literacy rate using AVG()
pd.read_sql("""
SELECT AVG(literacy_rate) AS avg_literacy_rate
FROM country_statistics
""", conn)

   avg_literacy_rate
0             97.248

In [26]:
# 13.Filter rows where literacy rate is greater than 90%
pd.read_sql("""
SELECT * FROM country_statistics
WHERE literacy_rate > 90
""", conn)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,United States,30500000,312000000,99.0,331002651,94.26,0.09
1,China,19230000,1080000000,97.2,1411778724,76.50,0.01
2,Japan,4180000,118000000,99.0,125836021,93.77,0.03
3,Germany,4744000,79000000,99.0,83240525,94.91,0.06
4,United Kingdom,3839000,66000000,99.0,67886011,97.22,0.06
5,France,3211000,62000000,99.0,65273511,94.98,0.05
6,Italy,2420000,56000000,99.0,60461826,92.62,0.04
7,Canada,2250000,36000000,99.0,38005238,94.72,0.06
8,Australia,1880000,24000000,99.0,25687041,93.43,0.07
9,Brazil,2330000,181000000,93.2,212559417,85.15,0.01
10,Russia,2200000,125000000,99.7,145934462,85.65,0.02
11,South Korea,1800000,50000000,98.8,51780579,96.56,0.03
12,Spain,1710000,44000000,98.6,46754778,94.11,0.04
13,Mexico,1810000,102000000,95.4,128932753,79.11,0.01
14,Indonesia,1500000,212000000,96.0,273523615,77.51,0.01
15,Saudi Arabia,1100000,34000000,97.3,34813871,97.66,0.03
16,Turkey,1350000,69000000,96.7,84339067,81.81,0.02
17,South Africa,410000,43000000,95.0,59308690,72.50,0.01
18,Argentina,640000,41000000,99.1,45195774,90.72,0.01
19,Netherlands,1150000,17000000,99.0,17441139,97.47,0.07
20,Switzerland,940000,8500000,99.0,8654622,98.21,0.11
21,Sweden,650000,10100000,99.0,10353442,97.55,0.06
22,Norway,580000,5300000,100.0,5421241,97.76,0.11
23,Singapore,530000,5600000,97.5,5850342,95.72,0.09

In [27]:
# 14.Sort by internet penetration (highest first) and get top 5
pd.read_sql("""
SELECT * FROM country_statistics
ORDER BY internet_penetration DESC
LIMIT 5
""", conn)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,Switzerland,940000,8500000,99.0,8654622,98.21,0.11
1,Norway,580000,5300000,100.0,5421241,97.76,0.11
2,Saudi Arabia,1100000,34000000,97.3,34813871,97.66,0.03
3,Sweden,650000,10100000,99.0,10353442,97.55,0.06
4,Netherlands,1150000,17000000,99.0,17441139,97.47,0.07

In [28]:
#15. Calculate total population using SUM()
pd.read_sql("""
SELECT SUM(population) AS total_population
FROM country_statistics
""", conn)

   total_population
0        4720039725

In [29]:
#16. Sort by GDP per capita and get the top country
pd.read_sql("""
SELECT * FROM country_statistics
ORDER BY gdp_per_capita DESC
LIMIT 1
""", conn)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,Switzerland,940000,8500000,99.0,8654622,98.21,0.11

In [30]:
#17. Save the merged DataFrame into a CSV file
merged_df.to_csv('country_statistics.csv', index=False)

print("CSV file exported successfully!")

CSV file exported successfully!

In [31]:
#18. Sort by GDP per capita (highest first) and show top 10
pd.read_sql("""
SELECT * FROM country_statistics
ORDER BY gdp_per_capita DESC
LIMIT 10
""", conn)

,country,gdp,internet_users,literacy_rate,population,internet_penetration,gdp_per_capita
0,Switzerland,940000,8500000,99.0,8654622,98.21,0.11
1,Norway,580000,5300000,100.0,5421241,97.76,0.11
2,United States,30500000,312000000,99.0,331002651,94.26,0.09
3,Singapore,530000,5600000,97.5,5850342,95.72,0.09
4,Australia,1880000,24000000,99.0,25687041,93.43,0.07
5,Netherlands,1150000,17000000,99.0,17441139,97.47,0.07
6,Germany,4744000,79000000,99.0,83240525,94.91,0.06
7,United Kingdom,3839000,66000000,99.0,67886011,97.22,0.06
8,Canada,2250000,36000000,99.0,38005238,94.72,0.06
9,Sweden,650000,10100000,99.0,10353442,97.55,0.06

ETL Process Summary

Data Sources Used:
Data was collected from multiple sources including Excel (GDP data), JSON (internet users), and CSV files (literacy rate and population).

Data Cleaning Steps:
Column names were standardized (converted to lowercase, removed spaces), and renamed to ensure a common key column (country) across all datasets.

Transformations Performed:
Data types were converted to numeric format, and new columns such as Internet Penetration (%) and GDP Per Capita were calculated and rounded.

Data Merging:
All datasets were merged into a single DataFrame using the common column country.

Database Loading Process:
The final dataset was stored in a SQLite database (country_data.db) in a table named country_statistics.

Key Insights Obtained:
Analysis revealed top countries by GDP and population, average literacy and internet usage, and a positive correlation between literacy rate and internet penetration